services:
  - type: web
    name: symfony-app
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: dev
      - key: APP_SECRET
        value: cd4d7e9398b343c2845fd03f8a72b9b179af8c4e8e49f3e4f77a2f149fd7a4fa
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: COMPOSER_ALLOW_SUPERUSER
        value: 1

databases:
  - name: symfony-db
    plan: starter
    region: oregon