services:
  - type: web
    name: symfony-render-app
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        value: 425812b0ef16a08cfd251b4ac861a4c8
      - key: DATABASE_URL
        value: postgresql://root:ONySL36hkQ5bywATYlM1jK1Z4wySP5WR@dpg-cvo2jlc9c44c73bhmvb0-a/cardsnshots
    runtime: docker
